package exceptions;

public class AutoGeneratedIDException extends Exception {

	private static final long serialVersionUID = 1L;

	public AutoGeneratedIDException() {
		// TODO Auto-generated constructor stub
	}

	public AutoGeneratedIDException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public AutoGeneratedIDException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}

	public AutoGeneratedIDException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public AutoGeneratedIDException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

}
